name: Build & Test

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
        QC_IB_ACCOUNT: ${{ secrets.QC_IB_ACCOUNT }}
        QC_IB_USER_NAME: ${{ secrets.QC_IB_USER_NAME }}
        QC_IB_PASSWORD: ${{ secrets.QC_IB_PASSWORD }}
        QC_IB_TRADING_MODE: ${{ secrets.QC_IB_TRADING_MODE }}
        QC_IB_AGENT_DESCRIPTION: ${{ secrets.QC_IB_AGENT_DESCRIPTION }}
        QC_IB_TWS_DIR: ${{ secrets.QC_IB_TWS_DIR }}
        QC_IB_ENABLE_DELAYED_STREAMING_DATA: ${{ secrets.QC_IB_ENABLE_DELAYED_STREAMING_DATA }}
        QC_IB_HOST: ${{ secrets.QC_IB_HOST }}
        QC_JOB_USER_ID: ${{ secrets.JOB_USER_ID }}
        QC_API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
        QC_JOB_ORGANIZATION_ID: ${{ secrets.JOB_ORGANIZATION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Checkout Lean Same Branch
        id: lean-same-branch
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean

      - name: Checkout Lean Master
        if: steps.lean-same-branch.outcome != 'success'
        uses: actions/checkout@v2
        with:
          repository: QuantConnect/Lean
          path: Lean

      - name: Move Lean
        run: mv Lean ../Lean

      - name: Run Image
        uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation
          options: --workdir /__w/Lean.Brokerages.InteractiveBrokers/Lean.Brokerages.InteractiveBrokers -v /home/runner/work:/__w
          shell: bash
          run: |
            # Build
            dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.InteractiveBrokersBrokerage.sln
            # Run Tests
            dotnet test ./QuantConnect.InteractiveBrokersBrokerage.Tests/bin/Release/QuantConnect.InteractiveBrokersBrokerage.Tests.dll
